name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scalaversion: ["2.11.12", "2.12.11", "2.13.2", "3.x"]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          java-version: 8
          distribution: adopt
      - uses: sbt/setup-sbt@v1
      - uses: coursier/cache-action@v6
      - name: Build
        run: sbt "++${{ matrix.scalaversion }}" publishLocal
      - name: MiMa
        run: sbt "++${{ matrix.scalaversion }}" mimaReportBinaryIssues
      - name: Header check
        run: sbt "++${{ matrix.scalaversion }}" headerCheck
